version: "3"
services:
  db:
    build: ./db
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    networks:
      - keijiban
    restart: always
    volumes:
      - "./var/lib/mysql:/var/lib/mysql"

  rest:
    build: ./rest
    container_name: rest
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_ROOT_USER=root
      - DB_ROOT_PASSWORD=root
      - DB_NAME=bulletin_board
    expose:
      - 3000
    networks:
      - keijiban
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /src/node_modules

  app:
    build: ./app
    container_name: app
    depends_on:
      - db
      - rest
    environment:
      - BASIC_AUTH_USERNAME=user
      - BASIC_AUTH_PASSWORD=password
    networks:
      - keijiban
    ports:
      - '80:8080'
    restart: always
    volumes:
      - /src/node_modules

networks:
  keijiban:
