version: "3"
services:
  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./var/lib/mysql:/var/lib/mysql"
    restart: always

  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - /src/node_modules
    links:
      - db
    restart: always
